# ferry house config file

# Ferryboat 访问信息
ferry.address=211.157.179.37
ferry.port=7900

# 授权文件
#licence=config/licence

# 数据库配置
#mysql.host=127.0.0.1
#mysql.port=3306
#mysql.schema=cube
#mysql.user=cube_3
#mysql.password=ferryhouse

# Gnosis 配置
gnosis.host=192.168.1.82
gnosis.port=3000
