# console.properties

# DB
db=mysql

# MySQL config
mysql.host=211.157.179.34
mysql.port=3306
mysql.schema=lens_console
mysql.user=baize
mysql.password=Baizejingzhi#2023

# Auth DB config
auth.mysql.host=211.157.179.34
auth.mysql.port=3306
auth.mysql.schema=lens
auth.mysql.user=baize
auth.mysql.password=Baizejingzhi#2023

# Statistic DB config
statistic.mysql.host=211.157.179.34
statistic.mysql.port=3306
statistic.mysql.schema=lens
statistic.mysql.user=baize
statistic.mysql.password=Baizejingzhi#2023
